DROP TABLE IF EXISTS TBL_RESERVATIONS;

CREATE TABLE TBL_RESERVATIONS (
  id INT AUTO_INCREMENT  PRIMARY KEY,
  studentName VARCHAR(250) NOT NULL,
  studentEmail VARCHAR(250) NOT NULL,
  courseId VARCHAR(250) NOT NULL,
  reservationDate VARCHAR(250) NOT NULL
);


CREATE TABLE TBL_COURSES (
  id INT AUTO_INCREMENT  PRIMARY KEY,
  courseName VARCHAR(250) NOT NULL,
  courseDate VARCHAR(250) NOT NULL,
  numberOfSeats INT NOT NULL
);